spring.application.name=02_UserManagement_App

#Data Source Properties
spring.datasource.url=jdbc:mysql://localhost:3306/jrtp27
spring.datasource.username=root
spring.datasource.password=sonu@2022#1


#ORM Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#SMTP Properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ssah6477@gmail.com
spring.mail.password=pzbr yzlt phzx otog
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

